import { Button } from '@mui/material'

export default function Home() {
  return (
    <>
      <Button
        variant="contained"
        color="error"
      >
        error
      </Button>
      <Button
        variant="contained"
        color="info"
      >
        info
      </Button>
      <Button
        variant="contained"
        color="inherit"
      >
        inherit
      </Button>
      <Button
        variant="contained"
        color="primary"
      >
        primary
      </Button>
      <Button
        variant="contained"
        color="secondary"
      >
        secondary
      </Button>
      <Button
        variant="contained"
        color="success"
      >
        success
      </Button>
      <Button
        variant="contained"
        color="warning"
      >
        warning
      </Button>
    </>
  )
}
